---
name: Check formatting

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: check-formatting-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "19"

      - uses: actionsx/prettier@v3
        with:
          args: --check .
